### ISSUE TITLE
This plugin does not work with Grails 2.3.2

### ISSUE THREAD

**Issue by augustine-tran** [noamt/elasticsearch-grails-plugin#2]
I got this errors while run-app

```
Caused by BeanCreationException: Error creating bean with name 'elasticSearchClient': FactoryBean threw exception on object creation; nested exception is java.lang.NoClassDefFoundError: org/apache/lucene/util/Version
```
